### ISSUE TITLE
Remove default value for mandatory variables

### ISSUE THREAD

**Issue by claudiuskastner** [MULTIVAC-SE/terraform-azurerm-virtual-machine#3]
We should remove the default values for mandatory variables like:
- name
- location
- resource_group_name

See:
https://github.com/MULTIVAC-SE/terraform-azurerm-virtual-machine/blob/c50fd3825dce665616e4338f07d458249d32dcb3/variables.tf#L3

**Comment by schauppm** [comment]
Sollen wir das dann auch auf das vnet ausweiten? Eine VM ohne NIC wird es ja glaub ich auch nicht geben

**Comment by claudiuskastner** [comment]
Ja, am besten alles was gesetzt werden muss.
